using Content.Client.UserInterface.Controls;
using Content.Client.Pinpointer.UI;
using Content.Shared._VXS14.WeaponMonitoring;
using Content.Shared._VXS14.WeaponMonitoring.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client._VXS14.WeaponMonitoring;

[GenerateTypedNameReferences]
public sealed partial class WeaponMonitoringConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private readonly EntityUid _console;
    private readonly Dictionary<NetEntity, int> _markerIndex = new();
    private List<WeaponMonitoringConsoleEntry> _entries = new();
    private int? _selectedIndex;
    private bool _consoleAvailable = true;

    public Action? OnRefreshRequested;
    public Action<WeaponMonitoringControlAction, NetEntity>? OnControlActionRequested;

    public WeaponMonitoringConsoleWindow(EntityUid console)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        _console = console;

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        WeaponsList.OnItemSelected += args =>
        {
            _selectedIndex = args.ItemIndex;
            UpdateSelected(args.ItemIndex);
        };
        SetBombTargetButton.OnPressed += _ => TrySendAction(WeaponMonitoringControlAction.SetBombTarget);
        ControlGunButton.OnPressed += _ => TrySendAction(WeaponMonitoringControlAction.ControlGun);
        LaunchRocketButton.OnPressed += _ => TrySendAction(WeaponMonitoringControlAction.LaunchRocket);
        WeaponsMap.Owner = _console;
        WeaponsMap.TrackedEntitySelectedAction += OnMapEntitySelected;

        SetStationName(null);
        ClearSelection();
    }

    public void UpdateState(WeaponMonitoringConsoleState state)
    {
        _consoleAvailable = !state.PlanetaryMap;
        RefreshButton.Disabled = !_consoleAvailable;
        WeaponsMap.Visible = _consoleAvailable;
        PlanetaryDisabledLabel.Visible = !_consoleAvailable;

        SetStationName(state.ConsoleGrid);
        UpdateMap(state);

        var previousEntity = GetSelectedEntity();

        _entries = state.Entries;
        WeaponsList.Clear();

        for (var index = 0; index < _entries.Count; index++)
        {
            var entry = _entries[index];
            var category = Loc.GetString(GetCategoryLocKey(entry.Category));
            WeaponsList.AddItem($"[{category}] {entry.Name}");
        }

        if (!_consoleAvailable || _entries.Count == 0)
        {
            _selectedIndex = null;
            ClearSelection();
            return;
        }

        var selectedIndex = previousEntity == null
            ? 0
            : _entries.FindIndex(x => x.Entity == previousEntity.Value);

        if (selectedIndex < 0)
            selectedIndex = 0;

        WeaponsList.ClearSelected();
        WeaponsList[selectedIndex].Selected = true;
        _selectedIndex = selectedIndex;
        UpdateSelected(selectedIndex);
    }

    private void SetStationName(NetEntity? consoleGrid)
    {
        var stationName = Loc.GetString("power-monitoring-window-unknown-location");

        if (consoleGrid is { } gridNet)
        {
            var gridUid = _entManager.GetEntity(gridNet);
            if (_entManager.TryGetComponent(gridUid, out MetaDataComponent? stationMetaData))
                stationName = stationMetaData.EntityName;
        }
        else if (_entManager.TryGetComponent(_console, out TransformComponent? xform) &&
                 xform.GridUid != null &&
                 _entManager.TryGetComponent(xform.GridUid, out MetaDataComponent? consoleGridMetaData))
        {
            stationName = consoleGridMetaData.EntityName;
        }

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("weapon-monitoring-window-station-name", ("stationName", stationName)));
        StationName.SetMessage(msg);
    }

    private NetEntity? GetSelectedEntity()
    {
        if (_selectedIndex == null || _selectedIndex < 0 || _selectedIndex >= _entries.Count)
            return null;

        return _entries[_selectedIndex.Value].Entity;
    }

    private void UpdateSelected(int index)
    {
        if (index < 0 || index >= _entries.Count)
        {
            ClearSelection();
            return;
        }

        _selectedIndex = index;

        var entry = _entries[index];
        SelectedWeaponName.Text = entry.Name;
        CategoryValue.Text = Loc.GetString(GetCategoryLocKey(entry.Category));
        FovValue.Text = FormatValue(entry.Fov, "weapon-monitoring-window-fov-value");
        SeekerValue.Text = string.IsNullOrWhiteSpace(entry.SeekerType)
            ? Loc.GetString("weapon-monitoring-window-value-unknown")
            : entry.SeekerType;
        WarheadValue.Text = string.IsNullOrWhiteSpace(entry.WarheadType)
            ? Loc.GetString("weapon-monitoring-window-value-unknown")
            : entry.WarheadType;
        FlightTimeValue.Text = FormatValue(entry.FlightTime, "weapon-monitoring-window-flight-time-value");
        DeviationValue.Text = FormatValue(entry.Deviation, "weapon-monitoring-window-deviation-value");
        ProjectileSpeedValue.Text = FormatValue(entry.ProjectileSpeed, "weapon-monitoring-window-speed-value");
        LockedTargetValue.Text = string.IsNullOrWhiteSpace(entry.LockedTarget)
            ? Loc.GetString("weapon-monitoring-window-value-unknown")
            : entry.LockedTarget;

        var notes = string.IsNullOrWhiteSpace(entry.Notes)
            ? Loc.GetString("weapon-monitoring-window-notes-empty")
            : entry.Notes;

        NotesValue.SetMessage(notes);

        SetBombTargetButton.Disabled = !_consoleAvailable || entry.Category != WeaponMonitoringCategory.AerialBomb;
        ControlGunButton.Disabled = !_consoleAvailable || entry.Category != WeaponMonitoringCategory.NavalGun;
        LaunchRocketButton.Disabled = !_consoleAvailable
            || (entry.Category != WeaponMonitoringCategory.AntiShipMissile
                && entry.Category != WeaponMonitoringCategory.AntiMissile);
        UpdateMarkerSelection();
    }

    private void ClearSelection()
    {
        _selectedIndex = null;
        SelectedWeaponName.Text = Loc.GetString("weapon-monitoring-window-no-selection");
        CategoryValue.Text = "-";
        FovValue.Text = "-";
        SeekerValue.Text = "-";
        WarheadValue.Text = "-";
        FlightTimeValue.Text = "-";
        DeviationValue.Text = "-";
        ProjectileSpeedValue.Text = "-";
        LockedTargetValue.Text = "-";
        NotesValue.SetMessage(Loc.GetString("weapon-monitoring-window-notes-empty"));
        SetBombTargetButton.Disabled = true;
        ControlGunButton.Disabled = true;
        LaunchRocketButton.Disabled = true;
        UpdateMarkerSelection();
    }

    private void TrySendAction(WeaponMonitoringControlAction action)
    {
        if (!_consoleAvailable)
            return;

        var selected = GetSelectedEntity();
        if (selected == null)
            return;

        OnControlActionRequested?.Invoke(action, selected.Value);
    }

    private string FormatValue(float? value, string formatLocKey)
    {
        if (value == null)
            return Loc.GetString("weapon-monitoring-window-value-unknown");

        return Loc.GetString(formatLocKey, ("value", value.Value));
    }

    private string GetCategoryLocKey(WeaponMonitoringCategory category)
    {
        return category switch
        {
            WeaponMonitoringCategory.AntiShipMissile => "weapon-monitoring-window-category-missile",
            WeaponMonitoringCategory.AerialBomb => "weapon-monitoring-window-category-bomb",
            WeaponMonitoringCategory.NavalGun => "weapon-monitoring-window-category-gun",
            WeaponMonitoringCategory.AntiMissile => "weapon-monitoring-window-category-anti-missile",
            _ => "weapon-monitoring-window-value-unknown"
        };
    }

    private void UpdateMap(WeaponMonitoringConsoleState state)
    {
        _markerIndex.Clear();
        WeaponsMap.TrackedEntities.Clear();

        if (!_consoleAvailable)
            return;

        if (state.ConsoleGrid is { } gridNet)
        {
            var gridUid = _entManager.GetEntity(gridNet);
            WeaponsMap.MapUid = gridUid;
            WeaponsMap.ForceNavMapUpdate();
        }
        else
        {
            WeaponsMap.MapUid = null;
            WeaponsMap.ForceNavMapUpdate();
        }

        var blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_triangle.png")));

        for (var index = 0; index < state.Entries.Count; index++)
        {
            var entry = state.Entries[index];
            var coords = _entManager.GetCoordinates(entry.Coordinates);
            var color = GetCategoryColor(entry.Category);
            WeaponsMap.TrackedEntities[entry.Entity] = new NavMapBlip(coords, blipTexture, color, false, true, 1.15f);
            _markerIndex[entry.Entity] = index;
        }

        UpdateMarkerSelection();
    }

    private void OnMapEntitySelected(NetEntity? netEntity)
    {
        if (netEntity == null)
            return;

        if (!_markerIndex.TryGetValue(netEntity.Value, out var index))
            return;

        if (index < 0 || index >= _entries.Count)
            return;

        WeaponsList.ClearSelected();
        WeaponsList[index].Selected = true;
        _selectedIndex = index;
        UpdateSelected(index);
    }

    private void UpdateMarkerSelection()
    {
        var selected = GetSelectedEntity();

        var entities = new List<NetEntity>();
        foreach (var (entity, _) in WeaponsMap.TrackedEntities)
        {
            entities.Add(entity);
        }

        foreach (var entity in entities)
        {
            var marker = WeaponsMap.TrackedEntities[entity];
            var isSelected = selected != null && entity == selected.Value;
            marker.Blinks = isSelected;
            if (isSelected)
            {
                marker.Color = Color.Yellow;
            }
            else if (_markerIndex.TryGetValue(entity, out var idx) && idx >= 0 && idx < _entries.Count)
            {
                marker.Color = GetCategoryColor(_entries[idx].Category);
            }
            WeaponsMap.TrackedEntities[entity] = marker;
        }
    }

    private static Color GetCategoryColor(WeaponMonitoringCategory category)
    {
        return category switch
        {
            WeaponMonitoringCategory.AntiShipMissile => Color.OrangeRed,
            WeaponMonitoringCategory.AerialBomb => Color.LightGoldenrodYellow,
            WeaponMonitoringCategory.NavalGun => Color.CornflowerBlue,
            WeaponMonitoringCategory.AntiMissile => Color.LimeGreen,
            _ => Color.White
        };
    }
}
