- type: job
  id: SyndyCommander
  name: Field Commander
  description: Lead the 110th AGr SOF Triglav. Bear the weight of command and bring victory to the Syndicate.
  playTimeTracker: JobSyndyCommander
  startingGear: SyndyCommanderGear
  icon: "JobIconSyndyCommander"
  supervisors: job-supervisors-captain
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 55
    requiredAge: 55
    inverted: true
  - !type:SexRequirement
    sexes: [Male]
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 10
    deathMessage: "Syndy Field Commander KIA. -10 tickets"

- type: startingGear
  id: SyndyCommanderGear
  equipment:
    id: DogtagSyndyCommander
    ears: ClothingHeadsetAltSyndicate
