- type: job
  id: SyndyMarksman
  name: Marksman
  description: Eliminate designated targets with precision. One shot, one kill.
  playTimeTracker: JobSyndyMarksman
  startingGear: SyndyMarksmanGear
  icon: "JobIconSyndyMarksman"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 16
    requiredAge: 16
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SexRequirement
    sexes: [Male]
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Syndy Marksman KIA. -1 ticket"

- type: startingGear
  id: SyndyMarksmanGear
  equipment:
    id: DogtagSyndyMarksman
    ears: ClothingHeadsetAltSyndicate
  storage:
    back:
    - Rangefinder
    - HandheldGPSBasic
