- type: job
  id: SyndyMedic
  name: Combat Medic
  description: Keep the team operational. A dead operative is a failed investment.
  playTimeTracker: JobSyndyMedic
  startingGear: SyndyMedicGear
  icon: "JobIconSyndyMedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 16
    requiredAge: 16
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SexRequirement
    sexes: [Male]
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Syndy Combat Medic KIA. -1 ticket"

- type: startingGear
  id: SyndyMedicGear
  equipment:
    id: DogtagSyndyMedic
    ears: ClothingHeadsetAltSyndicate
