- type: job
  id: SyndyOperative
  name: Operative
  description: Execute your orders. The Syndicate does not tolerate failure.
  playTimeTracker: JobSyndyOperative
  startingGear: SyndyOperativeGear
  icon: "JobIconSyndyOperative"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SexRequirement
    sexes: [Male]
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Syndy Operative KIA. -1 ticket"

- type: startingGear
  id: SyndyOperativeGear
  equipment:
    id: DogtagSyndyOperative
    ears: ClothingHeadsetAltSyndicate
