- type: job
  id: SyndyPilot
  name: Pilot
  description: Fly the vehicles of the 110th AGr SOF Triglav. Get them in, get them out.
  playTimeTracker: JobSyndyPilot
  startingGear: SyndyPilotGear
  icon: "JobIconSyndyPilot"
  supervisors: job-supervisors-hos
  canBeAntag: false
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SexRequirement
    sexes: [Male]
  access:
  - Maintenance
  - External
  components:
  - type: RoleTicketCost
    ticketCost: 1
    deathMessage: "Syndy Pilot KIA. -1 ticket"

- type: startingGear
  id: SyndyPilotGear
  equipment:
    id: DogtagSyndyPilot
    ears: ClothingHeadsetAltSyndicate
    outerClothing: ClothingOuterEVASuitSyndicate
