using Content.Shared._VXS14.AerialBomb;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Localization;

namespace Content.Client._VXS14.AerialBomb;

public interface IAerialBombSelectionEui
{
    void SendDropRequest(NetEntity mapEntity);
}

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AerialBombWindow : DefaultWindow
{
    private IAerialBombSelectionEui? _eui;
    private readonly List<AerialBombEuiMsg.MapEntry> _maps = new();

    public AerialBombWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("aerial-bomb-ui-title");
        HeaderLabel.Text = Loc.GetString("aerial-bomb-ui-header");
        MapLabel.Text = Loc.GetString("aerial-bomb-ui-map");
        DropButton.Text = Loc.GetString("aerial-bomb-ui-drop");

        MapSelector.OnItemSelected += args => MapSelector.SelectId(args.Id);
        DropButton.OnPressed += _ => Submit();
    }

    public void SetEui(IAerialBombSelectionEui eui)
    {
        _eui = eui;
    }

    public void SetMaps(List<AerialBombEuiMsg.MapEntry> maps)
    {
        MapSelector.Clear();
        _maps.Clear();
        _maps.AddRange(maps);

        for (var i = 0; i < maps.Count; i++)
        {
            var map = maps[i];
            MapSelector.AddItem(map.Name, i);
        }

        var hasMaps = maps.Count > 0;
        MapSelector.Disabled = !hasMaps;
        DropButton.Disabled = !hasMaps;

        if (hasMaps)
            MapSelector.SelectId(0);
    }

    private void Submit()
    {
        if (MapSelector.Disabled)
            return;

        if (MapSelector.SelectedId < 0 || MapSelector.SelectedId >= _maps.Count)
            return;

        _eui?.SendDropRequest(_maps[MapSelector.SelectedId].MapEntity);
    }
}
